In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4], index=['X','Y'])

ser1


T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1, ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

df2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

df1

X         Y         Z
0  0.427121 -1.695038 -1.260499
1  0.929771  1.030273  0.088031
2 -0.926221 -0.248857  0.145053
3  0.350339 -1.244087  0.512281

In [13]:
df2

Y         Q         X
0 -0.990103 -1.057473  1.272717
1  1.571300  0.205324  1.562083
2  0.579368  0.013636 -1.048735

In [14]:
pd.concat([df1,df2])

X         Y         Z         Q
0  0.427121 -1.695038 -1.260499       NaN
1  0.929771  1.030273  0.088031       NaN
2 -0.926221 -0.248857  0.145053       NaN
3  0.350339 -1.244087  0.512281       NaN
0  1.272717 -0.990103       NaN -1.057473
1  1.562083  1.571300       NaN  0.205324
2 -1.048735  0.579368       NaN  0.013636

In [15]:
pd.concat([df1,df2], ignore_index=True)

X         Y         Z         Q
0  0.427121 -1.695038 -1.260499       NaN
1  0.929771  1.030273  0.088031       NaN
2 -0.926221 -0.248857  0.145053       NaN
3  0.350339 -1.244087  0.512281       NaN
4  1.272717 -0.990103       NaN -1.057473
5  1.562083  1.571300       NaN  0.205324
6 -1.048735  0.579368       NaN  0.013636